# Generated by Django 4.0.3 on 2022-04-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('funding_nums', models.IntegerField()),
            ],
            options={
                'db_table': 'fundings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('target_amount', models.IntegerField()),
                ('amount_per_session', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('achivement_rate', models.IntegerField()),
                ('end_date', models.CharField(max_length=20)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.publisher')),
                ('user', models.ManyToManyField(through='products.Funding', to='members.user')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='funding',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='funding',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.user'),
        ),
    ]
